2016/03/12 14:39:43 [error] 6752#0: *1 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 192.168.1.106, server: localhost, request: "GET /admin HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "192.168.1.106:8061"
2016/03/12 14:39:43 [error] 6752#0: *1 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 192.168.1.106, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "192.168.1.106:8061", referrer: "http://192.168.1.106:8061/admin"
2016/03/12 14:39:59 [error] 6752#0: *1 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 192.168.1.106, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "192.168.1.106:8061", referrer: "http://192.168.1.106:8061/admin"
2016/03/12 14:40:57 [error] 6752#0: *1 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 192.168.1.106, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "192.168.1.106:8061"
2016/03/12 14:40:58 [error] 6752#0: *1 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 192.168.1.106, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "192.168.1.106:8061", referrer: "http://192.168.1.106:8061/admin/"
2016/03/12 19:54:57 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338393&latitude=23.185012& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:57 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338405&latitude=23.185046& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:57 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338412&latitude=23.185067& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:57 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338413&latitude=23.185077& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:58 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338425&latitude=23.185087& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:58 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338424&latitude=23.185086& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:58 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338425&latitude=23.185067& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:58 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338424&latitude=23.185071& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:58 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:58 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:59 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:59 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:59 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:59 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:59 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:59 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:59 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:54:59 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:55:01 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:55:02 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 19:55:03 [error] 6916#0: *161 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338427&latitude=23.185072& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:17 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338223&latitude=23.185431& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:17 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338223&latitude=23.185431& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:17 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338241&latitude=23.185191& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:17 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338246&latitude=23.185116& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:18 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.33825&latitude=23.18509& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:18 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338248&latitude=23.18508& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:18 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338253&latitude=23.185035& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:18 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338253&latitude=23.185026& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:18 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338262&latitude=23.185008& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:18 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338266&latitude=23.184991& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:19 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.33828&latitude=23.184973& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:21 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338295&latitude=23.18496& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:23 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338297&latitude=23.184945& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 20:01:26 [error] 12626#0: *334 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338285&latitude=23.184926& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:07:43 [error] 12836#0: *2445 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338335&latitude=23.184961& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:07:46 [error] 12836#0: *2445 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338335&latitude=23.184961& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:07:48 [error] 12836#0: *2445 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338305&latitude=23.184905& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:07:49 [error] 12836#0: *2445 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338287&latitude=23.184888& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:07:51 [error] 12836#0: *2445 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338282&latitude=23.184876& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:07:53 [error] 12836#0: *2445 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338285&latitude=23.184876& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:12:03 [error] 14216#0: *2562 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338363&latitude=23.18499& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:12:04 [error] 14216#0: *2562 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338357&latitude=23.184994& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:12:05 [error] 14216#0: *2562 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338353&latitude=23.185& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:12:07 [error] 14216#0: *2562 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338335&latitude=23.184998& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:12:09 [error] 14216#0: *2562 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 100.64.135.34, server: localhost, request: "GET /oto/getshopList?lontitude=113.338315&latitude=23.18499& HTTP/1.1", upstream: "uwsgi://127.0.0.1:8077", host: "api.grayweb.cn:8061"
2016/03/12 21:17:45 [error] 14366#0: *2621 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:18:10 [error] 14366#0: *2623 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:19:03 [error] 14366#0: *2623 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:24:16 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:24:19 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:24:23 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:24:34 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:24:48 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:24:52 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:24:55 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:25:01 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:25:12 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:25:12 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/12 21:25:33 [error] 14366#0: *2625 open() "/Users/engine/lean/foodoto/server/otoserver/image/image/shop/IMG_0143.JPG" failed (2: No such file or directory), client: 100.64.135.34, server: localhost, request: "GET /image/image/shop/IMG_0143.JPG HTTP/1.1", host: "api.grayweb.cn:8061"
2016/03/13 21:40:02 [error] 15265#0: *99 open() "/Users/engine/lean/foodoto/server/otoserver/image/menu/IMG_0116.JPG" failed (2: No such file or directory), client: 192.168.1.100, server: localhost, request: "GET /image/menu/IMG_0116.JPG HTTP/1.1", host: "192.168.1.106:8061"
2016/03/13 21:40:11 [error] 15265#0: *103 open() "/Users/engine/lean/foodoto/server/otoserver/image/menu/IMG_0116.JPG" failed (2: No such file or directory), client: 192.168.1.106, server: localhost, request: "GET /image/menu/IMG_0116.JPG HTTP/1.1", host: "192.168.1.106:8061"
